Sonarqube: Clarify that nodeport can be used
Oteemo/charts pull request #286
Opened 2021-05-20 12:15 UTC by yamaken1343

This chart has already been implemented that the ports.nodePort on Service can be used.
However, values.yaml have no parameters. 
Show it in values.yaml so everyone can use the nodePort.

2021-05-24 17:47 UTC, rjkernick commented
Thanks for the PR, please increment the version in Chart.yaml

2021-05-25 17:42 UTC, rjkernick requested changes
Please increment the version in chart.yaml

2021-05-27 11:19 UTC, yamaken1343 commented
Thanks for review! I have updated the version in Chart.yaml.

2021-06-10 14:46 UTC, rjkernick approved these changes

2021-06-10 14:46 UTC, merged